version: "3.8"

services:
  web:
    build: .
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - "${PROJECT_PATH}:/var/www/html"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${PROJECT_PATH}"
      ACCEPT_EULA: "Y"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:

networks:
  app-network:
    external: true
